// <auto-generated />
using System;
using EducacaoXpert.GestaoConteudos.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducacaoXpert.GestaoConteudos.Data.Migrations
{
    [DbContext(typeof(GestaoConteudosContext))]
    partial class GestaoConteudosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Aulas", (string)null);
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Preco")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioCriacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.ToTable("Materiais", (string)null);
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.ProgressoAula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Assistindo")
                        .HasColumnType("bit");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProgressoCursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("ProgressoCursoId");

                    b.ToTable("ProgressoAulas", (string)null);
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.ProgressoCurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AulasFinalizadas")
                        .HasColumnType("int");

                    b.Property<bool>("CertificadoGerado")
                        .HasColumnType("bit");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PercentualConcluido")
                        .HasColumnType("int");

                    b.Property<int>("TotalAulas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId", "AlunoId")
                        .IsUnique();

                    b.ToTable("ProgressoCursos", (string)null);
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.Aula", b =>
                {
                    b.HasOne("EducacaoXpert.GestaoConteudos.Domain.Entities.Curso", "Curso")
                        .WithMany("Aulas")
                        .HasForeignKey("CursoId")
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.Material", b =>
                {
                    b.HasOne("EducacaoXpert.GestaoConteudos.Domain.Entities.Aula", "Aula")
                        .WithMany("Materiais")
                        .HasForeignKey("AulaId")
                        .IsRequired();

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.ProgressoAula", b =>
                {
                    b.HasOne("EducacaoXpert.GestaoConteudos.Domain.Entities.Aula", "Aula")
                        .WithMany("ProgressoAulas")
                        .HasForeignKey("AulaId")
                        .IsRequired();

                    b.HasOne("EducacaoXpert.GestaoConteudos.Domain.Entities.ProgressoCurso", "ProgressoCurso")
                        .WithMany("ProgressoAulas")
                        .HasForeignKey("ProgressoCursoId")
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("ProgressoCurso");
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.ProgressoCurso", b =>
                {
                    b.HasOne("EducacaoXpert.GestaoConteudos.Domain.Entities.Curso", "Curso")
                        .WithMany("ProgressoCursos")
                        .HasForeignKey("CursoId")
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.Aula", b =>
                {
                    b.Navigation("Materiais");

                    b.Navigation("ProgressoAulas");
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Aulas");

                    b.Navigation("ProgressoCursos");
                });

            modelBuilder.Entity("EducacaoXpert.GestaoConteudos.Domain.Entities.ProgressoCurso", b =>
                {
                    b.Navigation("ProgressoAulas");
                });
#pragma warning restore 612, 618
        }
    }
}
